### ISSUE TITLE
 tns generate service -- broken

### ISSUE THREAD

**Issue by allnash** [sebawita/nativescript-angular-cli#10]
Please run commands:

```
tns update // NOTE: this will update tools and templates to 5.0
tns generate service authentication
```

Error:

```
Error: Schematic input does not validate against the Schema: {"flat":true,"spec":true,"lintFix":false}
Errors:

  Data path "" should have required property 'name'.
    at t.schema.t.schemaJson.e.compile.pipe.o.map.e [as project] (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:447:403)
    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:24:13838)
    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)
    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:24:35146)
    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)
    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:24:36093)
    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)
    at t.notifyNext (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:2232)
    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:5749)
    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)
```

**Comment by mbahojlo** [comment]
Have you found a solution to this problem?

**Comment by AmitGurbani** [comment]
Try using angular cli

ng generate service service-name
