### ISSUE TITLE
Error: ENOENT: no such file or directory when trying to generate component

### ISSUE THREAD

**Issue by elcreator** [sebawita/nativescript-angular-cli#12]
Using default Nativescript tabbed app from Sidekick I have tried generate component abc and got an error:

$ tns generate c abc

CREATE /src/app/abc/abc.component.ts (280 bytes)

CREATE /src/app/abc/abc.component.css (49 bytes)

CREATE /src/app/abc/abc.component.html (59 bytes)

UPDATE /src/app/app.module.ts (693 bytes)

Error: ENOENT: no such file or directory, stat '/Users/myuser/projects/myproject-client/Myproject/platforms/ios/build/device/Myproject.app'

    at Object.fs.statSync (fs.js:948:11)

    at e.i.Observable.t [as _subscribe] (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/webpack:/@nativescript/schematics-executor/node_modules/@angular-devkit/core/node/host.js:263:0)

    at e._trySubscribe (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/webpack:/@nativescript/schematics-executor/node_modules/rxjs/_esm5/internal/Observable.js:42:0)

    at e.subscribe (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/webpack:/@nativescript/schematics-executor/node_modules/rxjs/_esm5/internal/Observable.js:28:0)

    at e.call (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/webpack:/@nativescript/schematics-executor/node_modules/rxjs/_esm5/internal/operators/map.js:18:0)

    at e.subscribe (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/webpack:/@nativescript/schematics-executor/node_modules/rxjs/_esm5/internal/Observable.js:23:0)

    at MergeMapSubscriber.originalBackend.list.pipe.operators_1.concatMap.path [as project] (/Users/myuser/projects/myproject-client/Myproject/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:353:51)

    at MergeMapSubscriber._tryNext (/Users/myuser/projects/myproject-client/Myproject/node_modules/rxjs/src/internal/operators/mergeMap.ts:132:20)

    at MergeMapSubscriber._next (/Users/myuser/projects/myproject-client/Myproject/node_modules/rxjs/src/internal/operators/mergeMap.ts:122:11)

    at MergeMapSubscriber.Subscriber.next (/Users/myuser/projects/myproject-client/Myproject/node_modules/rxjs/src/internal/Subscriber.ts:101:11)

**Comment by elcreator** [comment]
actually /Users/myuser/projects/myproject-client/Myproject/platforms/ios/build/device/Myproject.app exists but this it's symlink to /Users/myuser/Library/Developer/Xcode/DerivedData/Myproject-abcdsomehashlikelettersabcd/Build/Intermediates.noindex/ArchiveIntermediates/Myproject/InstallationBuildProductsLocation/Applications/Myproject.app
Looks like this is bug about symlink resolution
