### ISSUE TITLE
Error: Schematic input does not validate against the Schema: {"flat":true,"spec":true,"lintFix":false}

### ISSUE THREAD

**Issue by elcreator** [sebawita/nativescript-angular-cli#13]
$ tns generate service abc

Error: Schematic input does not validate against the Schema: {"flat":true,"spec":true,"lintFix":false}

Errors:

  Data path "" should have required property 'name'.

    at t.schema.t.schemaJson.e.compile.pipe.o.map.e [as project] (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:447:403)

    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:24:13838)

    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)

    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:24:35146)

    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)

    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:24:36093)

    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)

    at t.notifyNext (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:30:2232)

    at t._next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:5749)

    at t.next (/usr/local/lib/node_modules/nativescript/node_modules/@nativescript/schematics-executor/dist/index.js:16:1093)

**Comment by alessandrorodiani** [comment]
Any update here? I have the same issue

**Comment by carolgit** [comment]
Any update here? I have the same issue

**Comment by s-triar** [comment]
I have same issue for only `tns generate service <name-service>`

**Comment by flynsequeira** [comment]
Same issue

**Comment by Aamier** [comment]
Same Issue what's the solution
